(in-package #:cl-jobpond/tests)

;;;; -- Durable Coordination Tests --

(defvar *coordination-checks* 0)

(defun coordination--check (value)
  "Record one behavioral assertion."
  (incf *coordination-checks*)
  (unless value (error "Coordination assertion ~D failed." *coordination-checks*)))

(defmacro coordination--fails (reason &body body)
  "Check the typed reason from a rejected state transition."
  `(coordination--check
    (handler-case (progn ,@body nil)
      (cl-jobpond:durable-state-error (condition)
        (eq ,reason (cl-jobpond:durable-state-error-reason condition))))))

(defun coordination--roundtrip (value)
  "Roundtrip portable state with reader evaluation disabled."
  (with-standard-io-syntax
    (let ((*read-eval* nil)) (read-from-string (write-to-string value :readably t)))))

(defun coordination--schedule-tests ()
  "Exercise timing policies, identity, persistence and explicit uncertain outcomes."
  (dolist (policy '(:all :latest :skip))
    (let ((scheduler (cl-jobpond:make-scheduler :clock (lambda () 35))))
      (cl-jobpond:scheduler-add scheduler :id "periodic" :version "v1" :payload '(:work "hello")
                               :at 10 :interval 10 :missed-policy policy)
      (coordination--check (= (length (cl-jobpond:scheduler-wake scheduler))
                             (case policy (:all 3) (:latest 1) (:skip 0))))
      (coordination--check (= 40 (cl-jobpond:scheduler-next-time scheduler)))
      (coordination--check (null (cl-jobpond:scheduler-wake scheduler)))
      (coordination--check (= 1 (length (cl-jobpond:scheduler-wake scheduler :now 40))))
      (coordination--check (= 50 (cl-jobpond:scheduler-next-time scheduler)))))
  (let ((persisted nil) (fail nil) (now 20))
    (let ((scheduler (cl-jobpond:make-scheduler
                      :clock (lambda () now)
                      :store (lambda (snapshot)
                               (when fail (error "Injected atomic store refusal"))
                               (setf persisted (coordination--roundtrip snapshot))))))
      (cl-jobpond:scheduler-add scheduler :id "once" :version "v1" :payload '(:work "one") :at 20)
      (coordination--check (equal persisted (cl-jobpond:scheduler-snapshot scheduler)))
      (let ((payload (list :work "one")))
        (cl-jobpond:scheduler-add scheduler :id "once" :version "v1" :payload payload :at 20)
        (setf (second payload) "changed"))
      (coordination--fails ':identity-conflict
        (cl-jobpond:scheduler-add scheduler :id "once" :version "v2" :at 20))
      (cl-jobpond:scheduler-wake scheduler)
      (let* ((claim (cl-jobpond:scheduler-claim scheduler))
             (id (getf claim :id)) (token (getf claim :token))
             (recovered (cl-jobpond:make-scheduler :snapshot persisted)))
        (coordination--check (eq ':claimed (getf claim :state)))
        (coordination--check (eq ':unknown (getf (first (getf (cl-jobpond:scheduler-snapshot recovered) :wakeups)) :state)))
        (coordination--check (null (cl-jobpond:scheduler-claim recovered)))
        (coordination--fails ':stale-version
          (cl-jobpond:scheduler-claim recovered :id id :version "v2"))
        (cl-jobpond:scheduler-resolve recovered :id id :token token :action ':retry)
        (let ((new (cl-jobpond:scheduler-claim recovered :id id :version "v1")))
          (coordination--check (> (getf new :token) token))
          (coordination--fails ':stale-token
            (cl-jobpond:scheduler-ack recovered :id id :token token))
          (cl-jobpond:scheduler-ack recovered :id id :token (getf new :token) :result '(:proof "done"))
          (coordination--check
           (eq ':completed (getf (cl-jobpond:scheduler-ack recovered :id id
                                                          :token (getf new :token) :result '(:proof "done")) :state)))
          (coordination--fails ':outcome-conflict
            (cl-jobpond:scheduler-ack recovered :id id :token (getf new :token) :outcome ':failed))))
      (let ((before (cl-jobpond:scheduler-snapshot scheduler)))
        (setf fail t)
        (coordination--check
         (handler-case (progn (cl-jobpond:scheduler-cancel scheduler :id "once") nil)
           (error () t)))
        (coordination--check (equal before (cl-jobpond:scheduler-snapshot scheduler)))
        (setf fail nil))
      (cl-jobpond:scheduler-add scheduler :id "event" :version "e1" :event "build" :payload "finish")
      (coordination--check (= 1 (length (cl-jobpond:scheduler-event scheduler :event "build" :id "build1" :payload '(:ok t)))))
      (coordination--check (null (cl-jobpond:scheduler-event scheduler :event "build" :id "build1" :payload '(:ok t))))
      (coordination--fails ':identity-conflict
        (cl-jobpond:scheduler-event scheduler :event "build" :id "build1" :payload '(:ok nil)))
      (let ((claim (cl-jobpond:scheduler-claim scheduler)))
        (cl-jobpond:scheduler-cancel scheduler :id "event" :version "e1")
        (coordination--check (null (cl-jobpond:scheduler-event scheduler :event "build" :id "build2")))
        (coordination--fails ':cancelled
          (cl-jobpond:scheduler-resolve scheduler :id (getf claim :id) :token (getf claim :token) :action ':retry))
        (coordination--check
         (eq ':cancelled (getf (cl-jobpond:scheduler-ack scheduler :id (getf claim :id)
                                                       :token (getf claim :token) :outcome ':cancelled) :state))))
      (cl-jobpond:scheduler-close scheduler)
      (coordination--fails ':closed (cl-jobpond:scheduler-wake scheduler))
      (coordination--fails ':closed (cl-jobpond:scheduler-claim scheduler))
      (coordination--check (cl-jobpond:scheduler-close scheduler))))
  (let ((scheduler (cl-jobpond:make-scheduler :capacity 2)))
    (cl-jobpond:scheduler-add scheduler :id "catchup" :version "v1" :at 0 :interval 1 :missed-policy ':all)
    (let ((before (cl-jobpond:scheduler-snapshot scheduler)))
      (coordination--fails ':capacity (cl-jobpond:scheduler-wake scheduler :now 20))
      (coordination--check (equal before (cl-jobpond:scheduler-snapshot scheduler)))))
  (dolist (policy '(:all :latest :skip))
    (let ((scheduler (cl-jobpond:make-scheduler)))
      (cl-jobpond:scheduler-add scheduler :id "once" :version "v1" :at 3 :missed-policy policy)
      (coordination--check (= (length (cl-jobpond:scheduler-wake scheduler :now 4))
                             (if (eq policy ':skip) 0 1)))
      (coordination--check (null (cl-jobpond:scheduler-next-time scheduler)))))
  (coordination--fails ':snapshot (cl-jobpond:make-scheduler :snapshot '(:kind :scheduler :format 9))))

(defun coordination--mailbox-tests ()
  "Exercise bounded admission, ownership, recovery, waits and retained deduplication."
  (let ((persisted nil) (fail nil))
    (let ((mailbox (cl-jobpond:make-mailbox
                    :capacity 1 :history-limit 3 :clock (lambda () 42)
                    :store (lambda (snapshot)
                             (when fail (error "Injected store failure"))
                             (setf persisted (coordination--roundtrip snapshot))))))
      (let ((payload (list :text "hello")))
        (multiple-value-bind (message duplicate)
            (cl-jobpond:mailbox-send mailbox :id "m1" :sender "a" :receiver "b" :payload payload)
          (coordination--check (not duplicate))
          (coordination--check (= 42 (getf message :created-at)))
          (setf (second payload) "mutated")))
      (multiple-value-bind (message duplicate)
          (cl-jobpond:mailbox-send mailbox :id "m1" :sender "a" :receiver "b" :payload '(:text "hello"))
        (coordination--check duplicate)
        (coordination--check (eq ':queued (getf message :state))))
      (coordination--fails ':identity-conflict
        (cl-jobpond:mailbox-send mailbox :id "m1" :sender "other" :receiver "b" :payload '(:text "hello")))
      (coordination--fails ':capacity
        (cl-jobpond:mailbox-send mailbox :id "m2" :sender "a" :receiver "b"))
      (coordination--fails ':receiver (cl-jobpond:mailbox-receive mailbox :id "m1" :receiver "a"))
      (coordination--check (null (cl-jobpond:mailbox-receive mailbox :receiver "a")))
      (let* ((claim (cl-jobpond:mailbox-receive mailbox :receiver "b"))
             (token (getf claim :token))
             (recovered (cl-jobpond:make-mailbox :snapshot persisted)))
        (coordination--check (eq ':unknown (getf (cl-jobpond:mailbox-find recovered "m1") :state)))
        (coordination--check (null (cl-jobpond:mailbox-receive recovered :receiver "b")))
        (coordination--fails ':capacity (cl-jobpond:mailbox-send recovered :id "m2" :sender "a" :receiver "b"))
        (coordination--fails ':receiver (cl-jobpond:mailbox-ack recovered :id "m1" :receiver "a" :token token))
        (cl-jobpond:mailbox-resolve recovered :id "m1" :receiver "b" :token token :action ':retry)
        (let ((new (cl-jobpond:mailbox-receive recovered :receiver "b")))
          (coordination--check (> (getf new :token) token))
          (coordination--fails ':stale-token (cl-jobpond:mailbox-ack recovered :id "m1" :receiver "b" :token token))
          (cl-jobpond:mailbox-ack recovered :id "m1" :receiver "b" :token (getf new :token) :result "accepted")
          (coordination--check (eq ':acknowledged
                                  (getf (cl-jobpond:mailbox-ack recovered :id "m1" :receiver "b"
                                                             :token (getf new :token) :result "accepted") :state)))
          (coordination--fails ':outcome-conflict
            (cl-jobpond:mailbox-ack recovered :id "m1" :receiver "b" :token (getf new :token) :result "different")))
        (cl-jobpond:mailbox-send recovered :id "m2" :sender "a" :receiver "b")
        (coordination--fails ':sender (cl-jobpond:mailbox-cancel recovered :id "m2" :sender "c"))
        (cl-jobpond:mailbox-cancel recovered :id "m2" :sender "a")
        (coordination--check (eq ':cancelled (nth-value 1 (cl-jobpond:mailbox-wait recovered :id "m2" :timeout 0))))
        (cl-jobpond:mailbox-send recovered :id "m3" :sender "a" :receiver "b")
        (cl-jobpond:mailbox-cancel recovered :id "m3" :sender "a")
        (coordination--fails ':capacity (cl-jobpond:mailbox-send recovered :id "m4" :sender "a" :receiver "b"))
        (cl-jobpond:mailbox-close recovered)
        (coordination--check (nth-value 1 (cl-jobpond:mailbox-send recovered :id "m1" :sender "a" :receiver "b" :payload '(:text "hello"))))
        (coordination--fails ':closed (cl-jobpond:mailbox-send recovered :id "new" :sender "a" :receiver "b")))
      (let ((before (cl-jobpond:mailbox-snapshot mailbox)))
        (setf fail t)
        (coordination--check (handler-case (progn (cl-jobpond:mailbox-ack mailbox :id "m1" :receiver "b" :token 1) nil)
                              (error () t)))
        (coordination--check (equal before (cl-jobpond:mailbox-snapshot mailbox)))
        (setf fail nil))
      (cl-jobpond:mailbox-cancel mailbox :id "m1" :sender "a")
      (coordination--fails ':cancelled (cl-jobpond:mailbox-resolve mailbox :id "m1" :receiver "b" :token 1 :action ':retry))
      (cl-jobpond:mailbox-close mailbox)
      (coordination--check (eq ':closed (nth-value 1 (cl-jobpond:mailbox-wait mailbox :id "m1" :timeout 0))))
      (cl-jobpond:mailbox-ack mailbox :id "m1" :receiver "b" :token 1)
      (coordination--check (eq ':acknowledged (nth-value 1 (cl-jobpond:mailbox-wait mailbox :id "m1" :timeout 0))))))
  (let ((mailbox (cl-jobpond:make-mailbox)))
    (coordination--check (eq ':timeout (nth-value 1 (cl-jobpond:mailbox-wait mailbox :receiver "b" :timeout 0))))
    (coordination--check (eq ':cancelled (nth-value 1 (cl-jobpond:mailbox-wait mailbox :receiver "b" :cancelled-p (lambda () t)))))
    (coordination--fails ':not-found (cl-jobpond:mailbox-find mailbox "missing"))
    (coordination--fails ':nonportable-data (cl-jobpond:mailbox-send mailbox :id "m" :sender "a" :receiver "b" :payload #'identity))
    (let ((cycle (list "x")))
      (setf (rest cycle) cycle)
      (coordination--fails ':cyclic-data (cl-jobpond:mailbox-send mailbox :id "m" :sender "a" :receiver "b" :payload cycle)))
    (coordination--fails ':improper-list (cl-jobpond:mailbox-send mailbox :id "m" :sender "a" :receiver "b" :payload '(1 . 2))))
  (coordination--fails ':snapshot (cl-jobpond:make-mailbox :snapshot '(:kind :mailbox :format 1))))

(defun coordination--concurrency-tests ()
  "Prove atomic claim/admission and notification to multiple waiters."
  (let ((scheduler (cl-jobpond:make-scheduler)) (claims nil) (lock (make-lock)) (threads nil))
    (cl-jobpond:scheduler-add scheduler :id "once" :version "v1" :at 0)
    (cl-jobpond:scheduler-wake scheduler :now 0)
    (dotimes (i 16)
      (push (make-thread (lambda () (let ((claim (cl-jobpond:scheduler-claim scheduler)))
                                     (when claim (with-lock-held (lock) (push claim claims)))))) threads))
    (mapc #'join-thread threads)
    (coordination--check (= 1 (length claims))))
  (let ((mailbox (cl-jobpond:make-mailbox :capacity 1)) (results nil) (threads nil) (lock (make-lock)))
    (dotimes (i 16)
      (let ((id (format nil "m~D" i)))
        (push (make-thread (lambda ()
                             (let ((outcome (handler-case
                                                (progn (cl-jobpond:mailbox-send mailbox :id id :sender "a" :receiver "b") ':accepted)
                                              (cl-jobpond:durable-state-error () ':refused))))
                               (with-lock-held (lock) (push outcome results))))) threads)))
    (mapc #'join-thread threads)
    (coordination--check (= 1 (count ':accepted results)))
    (coordination--check (= 15 (count ':refused results))))
  (dolist (operation '(:send :close))
    (let ((mailbox (cl-jobpond:make-mailbox)) (results nil) (threads nil) (lock (make-lock)))
      (dotimes (i 8)
        (push (make-thread (lambda ()
                             (let ((outcome (nth-value 1 (cl-jobpond:mailbox-wait mailbox :receiver "b" :timeout 2))))
                               (with-lock-held (lock) (push outcome results))))) threads))
      (sleep 0.02)
      (if (eq operation ':send)
          (cl-jobpond:mailbox-send mailbox :id "m" :sender "a" :receiver "b")
          (cl-jobpond:mailbox-close mailbox))
      (mapc #'join-thread threads)
      (coordination--check (= 8 (count (if (eq operation ':send) ':queued ':closed) results))))))

(defun coordination--persistence-tests ()
  "Test real file snapshots, corrupted recovery and interrupted store publication."
  (let* ((pathname (merge-pathnames (format nil "jobpond-~A.sexp" (gensym)) (uiop:temporary-directory)))
         (temporary (make-pathname :type "new" :defaults pathname))
         (scheduler (cl-jobpond:make-scheduler
                     :store (lambda (snapshot)
                              (with-open-file (stream temporary :direction ':output :if-exists ':supersede)
                                (with-standard-io-syntax (write snapshot :stream stream :readably t)))
                              (uiop:rename-file-overwriting-target temporary pathname)))))
    (unwind-protect
         (progn
           (cl-jobpond:scheduler-add scheduler :id "file" :version "v1" :at 1)
           (cl-jobpond:scheduler-wake scheduler :now 1)
           (let ((claim (cl-jobpond:scheduler-claim scheduler)))
             (let* ((snapshot (with-open-file (stream pathname)
                                (let ((*read-eval* nil)) (read stream))))
                    (recovered (cl-jobpond:make-scheduler :snapshot snapshot)))
               (coordination--check (eq ':unknown (getf (first (getf (cl-jobpond:scheduler-snapshot recovered) :wakeups)) :state)))
               (coordination--check (null (cl-jobpond:scheduler-wake recovered :now 2)))
               (coordination--check (null (cl-jobpond:scheduler-claim recovered)))
               (cl-jobpond:scheduler-ack recovered :id (getf claim :id) :token (getf claim :token)))))
      (when (probe-file pathname) (delete-file pathname))
      (when (probe-file temporary) (delete-file temporary))))
  (let ((stored nil) (escape nil))
    (let ((scheduler (cl-jobpond:make-scheduler
                      :store (lambda (snapshot)
                               (setf stored snapshot)
                               (when escape (throw 'interrupted ':escaped))))))
      (cl-jobpond:scheduler-add scheduler :id "escape" :version "v1" :at 0)
      (cl-jobpond:scheduler-wake scheduler :now 0)
      (setf escape t)
      (coordination--check (eq ':escaped (catch 'interrupted (cl-jobpond:scheduler-claim scheduler))))
      (coordination--fails ':uncertain-store (cl-jobpond:scheduler-claim scheduler))
      (coordination--fails ':uncertain-store (cl-jobpond:scheduler-snapshot scheduler))
      (let ((recovered (cl-jobpond:make-scheduler :snapshot stored)))
        (coordination--check (null (cl-jobpond:scheduler-claim recovered)))
        (coordination--check (eq ':unknown (getf (first (getf (cl-jobpond:scheduler-snapshot recovered) :wakeups)) :state))))))
  (let* ((mailbox (cl-jobpond:make-mailbox)) (id (copy-seq "mutable")))
    (cl-jobpond:mailbox-send mailbox :id id :sender "a" :receiver "b")
    (setf (char id 0) #\X)
    (coordination--check (equal "mutable" (getf (cl-jobpond:mailbox-find mailbox "mutable") :id)))
    (let ((snapshot (cl-jobpond:mailbox-snapshot mailbox)))
      (setf (getf (first (getf snapshot :messages)) :state) ':nonsense)
      (coordination--fails ':snapshot (cl-jobpond:make-mailbox :snapshot snapshot)))
    (let ((snapshot (cl-jobpond:mailbox-snapshot mailbox)))
      (remf (first (getf snapshot :messages)) :result)
      (coordination--fails ':snapshot (cl-jobpond:make-mailbox :snapshot snapshot)))
    (let ((snapshot (cl-jobpond:mailbox-snapshot mailbox)))
      (setf (getf snapshot :closed) t)
      (coordination--fails ':snapshot (cl-jobpond:make-mailbox :snapshot snapshot))))
  (let ((scheduler (cl-jobpond:make-scheduler)))
    (cl-jobpond:scheduler-add scheduler :id "bad" :version "v1" :at 1)
    (cl-jobpond:scheduler-wake scheduler :now 1)
    (let ((snapshot (cl-jobpond:scheduler-snapshot scheduler)))
      (setf (getf (first (getf snapshot :wakeups)) :id) '("bad" "v2" (:time 1)))
      (coordination--fails ':snapshot (cl-jobpond:make-scheduler :snapshot snapshot)))
    (let ((snapshot (cl-jobpond:scheduler-snapshot scheduler)))
      (setf (getf (first (getf snapshot :schedules)) :at) -1)
      (coordination--fails ':snapshot (cl-jobpond:make-scheduler :snapshot snapshot)))))

(defun run-coordination-tests ()
  "Run optional scheduling and mailbox behavioral checks."
  (let ((*coordination-checks* 0))
    (coordination--schedule-tests)
    (coordination--mailbox-tests)
    (coordination--concurrency-tests)
    (coordination--persistence-tests)
    (format t "~&cl-jobpond coordination: ~D assertions passed.~%" *coordination-checks*)
    t))
