(defpackage #:cl-jobpond
  (:use #:cl)
  (:import-from #:bordeaux-threads
                #:condition-notify
                #:condition-wait
                #:current-thread
                #:interrupt-thread
                #:join-thread
                #:make-condition-variable
                #:make-lock
                #:make-thread
                #:thread-alive-p
                #:with-lock-held)
  (:export #:*default-maximum-batch-size*
           #:*default-maximum-concurrency*
           #:*default-maximum-live-jobs*
           #:*default-maximum-runtime-milliseconds*
           #:*default-terminal-retention-limit*
           #:*identifier-fragment-limit*
           #:*maximum-concurrency-limit*
           #:*monitor-poll-seconds*
           #:*progress-output-limit*
           #:*retained-progress-output-limit*
           #:*retained-report-limit*
           #:*shutdown-timeout-seconds*
           #:job
           #:job-aborted
           #:job-aborted-identifier
           #:job-aborted-message
           #:job-aborted-reason
           #:job-await
           #:job-cancel
           #:job-cancellation-reason
           #:job-cancellation-requested-p
           #:job-check-cancellation
           #:job-condition-report
           #:job-created-at
           #:job-deadline
           #:job-ended-at
           #:job-identifier
           #:job-index
           #:job-maximum-runtime-milliseconds
           #:job-name
           #:job-not-found
           #:job-not-found-identifier
           #:job-owner-identifiers
           #:job-payload
           #:job-pool
           #:job-pool-active-count
           #:job-pool-add-listener
           #:job-pool-capacity-exceeded
           #:job-pool-capacity-exceeded-limit
           #:job-pool-capacity-exceeded-limit-kind
           #:job-pool-capacity-exceeded-live-count
           #:job-pool-capacity-exceeded-requested-count
           #:job-pool-close
           #:job-pool-closed
           #:job-pool-closed-lifecycle-state
           #:job-pool-descendant-jobs
           #:job-pool-job-class
           #:job-pool-detach
           #:job-pool-descendant-jobs
           #:job-pool-job-class
           #:job-pool-detach-refused
           #:job-pool-descendant-jobs
           #:job-pool-job-class
           #:job-pool-detach-refused-reason
           #:job-pool-emit
           #:job-pool-error
           #:job-pool-error-message
           #:job-pool-find-job
           #:job-pool-invalid-entry
           #:job-pool-invalid-entry-entry
           #:job-pool-invalid-limit
           #:job-pool-invalid-limit-kind
           #:job-pool-invalid-limit-value
           #:job-pool-lifecycle-state
           #:job-pool-list-jobs
           #:job-pool-live-count
           #:job-pool-live-jobs
           #:job-pool-maximum-batch-size
           #:job-pool-maximum-concurrency
           #:job-pool-maximum-live-jobs
           #:job-pool-maximum-runtime-milliseconds
           #:job-pool-name
           #:job-pool-queued-count
           #:job-pool-refresh
           #:job-pool-remove-listener
           #:job-pool-submit
           #:job-pool-submit-batch
           #:job-pool-terminal-retention-limit
           #:job-progress-snapshot
           #:job-report-progress
           #:job-result
           #:job-root-identifier
           #:job-run-inline
           #:job-run-token
           #:job-snapshot
           #:job-started-at
           #:job-state
           #:job-terminal-p
           #:make-job-pool))

(defpackage #:cl-jobpond/tests
  (:use #:cl)
  (:import-from #:bordeaux-threads
                #:all-threads
                #:condition-notify
                #:condition-wait
                #:make-condition-variable
                #:make-lock
                #:thread-name
                #:with-lock-held)
  (:import-from #:cl-jobpond
                #:*progress-output-limit*
                #:*retained-progress-output-limit*
                #:job-aborted
                #:job-aborted-reason
                #:job-await
                #:job-cancel
                #:job-cancellation-reason
                #:job-cancellation-requested-p
                #:job-check-cancellation
                #:job-condition-report
                #:job-deadline
                #:job-identifier
                #:job-index
                #:job-maximum-runtime-milliseconds
                #:job-name
                #:job-not-found
                #:job-not-found-identifier
                #:job-owner-identifiers
           #:job-payload
                #:job-pool-active-count
                #:job-pool-add-listener
                #:job-pool-capacity-exceeded
                #:job-pool-capacity-exceeded-limit
                #:job-pool-capacity-exceeded-limit-kind
                #:job-pool-capacity-exceeded-live-count
                #:job-pool-capacity-exceeded-requested-count
                #:job-pool-close
                #:job-pool-closed
                #:job-pool-descendant-jobs
           #:job-pool-job-class
           #:job-pool-detach
                #:job-pool-descendant-jobs
           #:job-pool-job-class
           #:job-pool-detach-refused
                #:job-pool-descendant-jobs
           #:job-pool-job-class
           #:job-pool-detach-refused-reason
                #:job-pool-emit
                #:job-pool-error
                #:job-pool-find-job
                #:job-pool-invalid-entry
                #:job-pool-invalid-limit
                #:job-pool-invalid-limit-kind
                #:job-pool-lifecycle-state
                #:job-pool-list-jobs
                #:job-pool-live-count
                #:job-pool-live-jobs
                #:job-pool-name
                #:job-pool-queued-count
                #:job-pool-refresh
                #:job-pool-remove-listener
                #:job-pool-submit
                #:job-pool-submit-batch
                #:job-progress-snapshot
                #:job-report-progress
                #:job-result
           #:job-root-identifier
                #:job-run-inline
                #:job-run-token
                #:job-snapshot
                #:job-started-at
                #:job-state
                #:job-terminal-p
                #:make-job-pool)
  (:export #:run-tests))
